name: Deploy

on: [push]

jobs:
  run_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            branch_name=$(basename ${{ github.ref }})

            git checkout ${{ secrets.MAIN_BRANCH }}
            git fetch --all
            git reset --hard origin/$branch_name
            pip install -r requirements.txt
            systemctl --user restart ${{ secrets.SERVICE_NAME }}
            exit
